# Phase 3: Data Preparation

**CRISP-DM Phase Description:**  
This phase covers all activities to construct the final dataset from the initial raw data. Data preparation tasks are likely to be performed multiple times, and not in any prescribed order. This is typically the longest and most time-consuming phase of the CRISP-DM lifecycle.

---

In [66]:
# Standard library imports for this phase
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Display settings
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)
%matplotlib inline

In [67]:

# Display settings
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)
sns.set_style('whitegrid')
%matplotlib inline

In [68]:
DATA_PATH = "Train_data.csv"

import pandas as pd

df = pd.read_csv(DATA_PATH)
df.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,num_compromised,root_shell,su_attempted,num_root,num_file_creations,num_shells,num_access_files,num_outbound_cmds,is_host_login,is_guest_login,count,srv_count,serror_rate,srv_serror_rate,rerror_rate,srv_rerror_rate,same_srv_rate,diff_srv_rate,srv_diff_host_rate,dst_host_count,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,class
0,0,tcp,ftp_data,SF,491,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,0.0,0.0,0.0,0.0,1.00,0.00,0.00,150,25,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,normal
1,0,udp,other,SF,146,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,13,1,0.0,0.0,0.0,0.0,0.08,0.15,0.00,255,1,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,normal
2,0,tcp,private,S0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,123,6,1.0,1.0,0.0,0.0,0.05,0.07,0.00,255,26,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,anomaly
3,0,tcp,http,SF,232,8153,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,5,5,0.2,0.2,0.0,0.0,1.00,0.00,0.00,30,255,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,normal
4,0,tcp,http,SF,199,420,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,30,32,0.0,0.0,0.0,0.0,1.00,0.00,0.09,255,255,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,normal

---
### Task 1: Select Data

Decide on the data to be used for analysis. Consider which columns (features) and rows (records) to include or exclude based on:

- **Relevance:** Does this feature contribute to the data mining goal?
- **Data Quality:** Is the quality of this feature sufficient (e.g., too many missing values)?
- **Technical Constraints:** Are there limitations on data volume or specific feature types?

**Output:** A rationale for inclusion/exclusion of data, and the resulting subset.

**Instructions:** Select the columns and rows relevant to your analysis goal. Document your reasoning.

In [69]:
# TODO: Select the relevant columns and rows for your analysis.
# Document your rationale for including or excluding specific features.

# Example:
# columns_to_keep = ['feature_1', 'feature_2', 'target']
# columns_to_drop = ['id_column', 'irrelevant_column']
# drop_reason = {
#     'id_column': 'Unique identifier, not predictive',
#     'irrelevant_column': 'Not related to the data mining goal'
# }

# df_selected = df.drop(columns=columns_to_drop)
# print(f"Shape after column selection: {df_selected.shape}")
# Drop unnecessary columns (if they exist)
columns_to_drop = []

drop_reason = {
    # "id": "Unique identifier, not useful for prediction"
}

df_selected = df.drop(columns=columns_to_drop, errors='ignore')

print(f"Shape after column selection: {df_selected.shape}")

Shape after column selection: (25192, 42)

In [70]:
df_selected = df_selected.dropna()

print(f"Shape after row selection: {df_selected.shape}")

Shape after row selection: (25192, 42)

---
### Task 2: Clean Data

Raise data quality to the level required by the selected analysis techniques. Cleaning activities include:

- **Handle Missing Values:** Impute missing values (mean, median, mode, forward/backward fill) or remove rows/columns with excessive missing data.
- **Correct Errors:** Fix inaccurate or corrupted data entries.
- **Remove Duplicates:** Eliminate exact or near-duplicate records.
- **Handle Outliers:** Decide how to treat extreme values (keep, cap, transform, or remove).

**Instructions:** Apply appropriate cleaning techniques to address the data quality issues identified in Phase 2, Task 4.

In [71]:
# TODO: Handle missing values.
# Choose an appropriate strategy for each column.

# Example strategies:
# df_clean = df_selected.copy()

# Strategy 1: Impute numerical columns with the median
# numerical_cols = df_clean.select_dtypes(include=np.number).columns
# df_clean[numerical_cols] = df_clean[numerical_cols].fillna(df_clean[numerical_cols].median())

# Strategy 2: Impute categorical columns with the mode
# categorical_cols = df_clean.select_dtypes(include='object').columns
# for col in categorical_cols:
#     df_clean[col] = df_clean[col].fillna(df_clean[col].mode()[0])

# Strategy 3: Drop rows/columns with too many missing values
# df_clean = df_clean.dropna(thresh=len(df_clean) * 0.5, axis=1)  # Drop cols with >50% missing

# print(f"Missing values remaining: {df_clean.isnull().sum().sum()}")
df_clean = df_selected.copy()

# Numerical columns → fill with median
numerical_cols = df_clean.select_dtypes(include=np.number).columns
df_clean[numerical_cols] = df_clean[numerical_cols].fillna(df_clean[numerical_cols].median())

# Categorical columns → fill with mode
categorical_cols = df_clean.select_dtypes(include='object').columns
for col in categorical_cols:
    df_clean[col] = df_clean[col].fillna(df_clean[col].mode()[0])

print(f"Missing values remaining: {df_clean.isnull().sum().sum()}")

Missing values remaining: 0

In [72]:
# TODO: Remove duplicate records.

# before = len(df_clean)
# df_clean = df_clean.drop_duplicates()
# after = len(df_clean)
# print(f"Removed {before - after} duplicate rows. Remaining: {after} rows.")
before = len(df_clean)

df_clean = df_clean.drop_duplicates()

after = len(df_clean)

print(f"Removed {before - after} duplicate rows. Remaining: {after} rows.")

Removed 0 duplicate rows. Remaining: 25192 rows.

In [73]:
# TODO: Handle outliers.
# Choose a strategy: capping (winsorizing), removing, or transforming.

# Example: Cap outliers using the IQR method
# def cap_outliers_iqr(dataframe, column):
#     Q1 = dataframe[column].quantile(0.25)
#     Q3 = dataframe[column].quantile(0.75)
#     IQR = Q3 - Q1
#     lower_bound = Q1 - 1.5 * IQR
#     upper_bound = Q3 + 1.5 * IQR
#     dataframe[column] = dataframe[column].clip(lower=lower_bound, upper=upper_bound)
#     return dataframe

# for col in numerical_cols:
#     df_clean = cap_outliers_iqr(df_clean, col)
def cap_outliers_iqr(dataframe, column):
    Q1 = dataframe[column].quantile(0.25)
    Q3 = dataframe[column].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    dataframe[column] = dataframe[column].clip(lower=lower_bound, upper=upper_bound)
    return dataframe


# Apply to all numerical columns
for col in numerical_cols:
    df_clean = cap_outliers_iqr(df_clean, col)
preparation_notes = [
    "Irrelevant columns were checked and removed where necessary",
    "Missing values in numerical features were handled using median imputation",
    "Categorical missing values were filled using the mode",
    "Duplicate records were removed to avoid bias in the model",
    "Outliers were handled using the IQR capping method to reduce their impact"
]

for i, note in enumerate(preparation_notes, 1):
    print(f"{i}. {note}")

1. Irrelevant columns were checked and removed where necessary
2. Missing values in numerical features were handled using median imputation
3. Categorical missing values were filled using the mode
4. Duplicate records were removed to avoid bias in the model
5. Outliers were handled using the IQR capping method to reduce their impact

---
### Task 3: Construct Data (Feature Engineering)

This task involves creating new attributes (features) derived from existing ones that may be more useful for modelling. Common techniques include:

- **Derived Attributes:** Create new features from existing ones (e.g., extracting `year`, `month`, `day` from a datetime column; computing `total_spend = price * quantity`).
- **Binning / Discretisation:** Convert continuous variables into categorical bins (e.g., age groups).
- **Encoding Categorical Variables:** Convert categorical features into numerical representations (e.g., one-hot encoding, label encoding).
- **Scaling / Normalisation:** Scale numerical features to a common range (e.g., Min-Max scaling, Standardisation).

**Instructions:** Create new features or transform existing ones to improve model performance.

In [74]:
# TODO: Create derived attributes / new features.

# Example: Create a new feature from existing columns
# df_clean['new_feature'] = df_clean['feature_a'] / df_clean['feature_b']

# Example: Extract components from a datetime column
# df_clean['date_column'] = pd.to_datetime(df_clean['date_column'])
# df_clean['year'] = df_clean['date_column'].dt.year
# df_clean['month'] = df_clean['date_column'].dt.month
# df_clean['day_of_week'] = df_clean['date_column'].dt.dayofweek
# Example: Create a simple derived feature (only if columns exist)

df_clean['total_activity'] = df_clean.select_dtypes(include=np.number).sum(axis=1)

In [75]:
# TODO: Encode categorical variables.

# Example: One-hot encoding
# df_clean = pd.get_dummies(df_clean, columns=['categorical_col_1', 'categorical_col_2'], drop_first=True)

# Example: Label encoding for ordinal variables
# from sklearn.preprocessing import LabelEncoder
# le = LabelEncoder()
# df_clean['ordinal_col'] = le.fit_transform(df_clean['ordinal_col'])
df_clean = pd.get_dummies(df_clean, drop_first=True)

print(f"Shape after encoding: {df_clean.shape}")

Shape after encoding: (25192, 117)

In [76]:
# TODO: Scale / normalise numerical features if required.

# from sklearn.preprocessing import StandardScaler, MinMaxScaler

# scaler = StandardScaler()  # or MinMaxScaler()
# cols_to_scale = ['feature_1', 'feature_2']
# df_clean[cols_to_scale] = scaler.fit_transform(df_clean[cols_to_scale])
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

numerical_cols = df_clean.select_dtypes(include=np.number).columns

df_clean[numerical_cols] = scaler.fit_transform(df_clean[numerical_cols])

---
### Task 4: Integrate Data

If your project uses multiple data sources, this task involves merging or combining them into a single, unified dataset. Activities include:

- **Merging Tables:** Join datasets on common keys (e.g., using `pd.merge()`).
- **Appending Records:** Concatenate datasets with the same structure (e.g., using `pd.concat()`).
- **Aggregation:** Summarise data at a different level of granularity.

**Instructions:** If using multiple data sources, merge or concatenate them below. If your project uses a single dataset, document that here and proceed to the next task.

In [77]:
# TODO: Integrate data from multiple sources (if applicable).

# Example: Merge two DataFrames on a common key
# df_secondary = pd.read_csv('path/to/secondary_data.csv')
# df_integrated = pd.merge(df_clean, df_secondary, on='common_key', how='left')

# Example: Concatenate DataFrames with the same structure
# df_integrated = pd.concat([df_part1, df_part2], ignore_index=True)

# If using a single source, simply continue:
# df_integrated = df_clean.copy()
# print(f"Integrated dataset shape: {df_integrated.shape}")
df_integrated = df_clean.copy()

print(f"Integrated dataset shape: {df_integrated.shape}")

Integrated dataset shape: (25192, 117)

In [78]:
# Optional: Verify the integrated data
# df_integrated.head()
df_integrated.head()

,duration,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,num_compromised,root_shell,su_attempted,num_root,num_file_creations,num_shells,num_access_files,num_outbound_cmds,is_host_login,is_guest_login,count,srv_count,serror_rate,srv_serror_rate,rerror_rate,srv_rerror_rate,same_srv_rate,diff_srv_rate,srv_diff_host_rate,dst_host_count,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,total_activity,protocol_type_tcp,protocol_type_udp,service_X11,service_Z39_50,service_auth,service_bgp,service_courier,service_csnet_ns,service_ctf,service_daytime,service_discard,service_domain,service_domain_u,service_echo,service_eco_i,service_ecr_i,service_efs,service_exec,service_finger,service_ftp,service_ftp_data,service_gopher,service_hostnames,service_http,service_http_443,service_http_8001,service_imap4,service_iso_tsap,service_klogin,service_kshell,service_ldap,service_link,service_login,service_mtp,service_name,service_netbios_dgm,service_netbios_ns,service_netbios_ssn,service_netstat,service_nnsp,service_nntp,service_ntp_u,service_other,service_pm_dump,service_pop_2,service_pop_3,service_printer,service_private,service_red_i,service_remote_job,service_rje,service_shell,service_smtp,service_sql_net,service_ssh,service_sunrpc,service_supdup,service_systat,service_telnet,service_tim_i,service_time,service_urh_i,service_urp_i,service_uucp,service_uucp_path,service_vmnet,service_whois,flag_REJ,flag_RSTO,flag_RSTOS0,flag_RSTR,flag_S0,flag_S1,flag_S2,flag_S3,flag_SF,flag_SH,class_normal
0,0.0,1.415223,-0.672625,0.0,0.0,0.0,0.0,0.0,-0.807626,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.758456,-0.801133,-0.640142,-0.633978,0.0,0.0,0.772109,-0.693436,0.0,-0.328634,-0.813985,-0.779157,-0.271725,1.848086,-0.579656,-0.641804,-0.627365,0.0,0.0,-0.376881,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True
1,0.0,-0.113860,-0.672625,0.0,0.0,0.0,0.0,0.0,-0.807626,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.653417,-0.879920,-0.640142,-0.633978,0.0,0.0,-1.320567,2.768934,0.0,0.732059,-1.030895,-1.157831,2.544308,1.848086,-0.579656,-0.641804,-0.627365,0.0,0.0,-0.768314,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True
2,0.0,-0.760950,-0.672625,0.0,0.0,0.0,0.0,0.0,-0.807626,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.396970,-0.485985,1.595477,1.600209,0.0,0.0,-1.388806,0.922337,0.0,0.732059,-0.804947,-0.935081,0.116694,-0.663412,-0.579656,1.603834,1.614454,0.0,0.0,-0.771824,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False
3,0.0,0.267303,1.867994,0.0,0.0,0.0,0.0,0.0,1.238197,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.729809,-0.564772,-0.193018,-0.187141,0.0,0.0,0.772109,-0.693436,0.0,-1.540854,1.264742,1.069663,-0.854352,-0.161113,1.706748,-0.574435,-0.604947,0.0,0.0,1.443263,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True
4,0.0,0.121043,0.132324,0.0,0.0,0.0,0.0,0.0,1.238197,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.491085,1.562475,-0.640142,-0.633978,0.0,0.0,0.772109,-0.693436,0.0,0.732059,1.264742,1.069663,-0.854352,-0.663412,-0.579656,-0.641804,-0.627365,0.0,0.0,0.426048,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True

In [79]:
print(df_integrated.columns.tolist())

['duration', 'src_bytes', 'dst_bytes', 'land', 'wrong_fragment', 'urgent', 'hot', 'num_failed_logins', 'logged_in', 'num_compromised', 'root_shell', 'su_attempted', 'num_root', 'num_file_creations', 'num_shells', 'num_access_files', 'num_outbound_cmds', 'is_host_login', 'is_guest_login', 'count', 'srv_count', 'serror_rate', 'srv_serror_rate', 'rerror_rate', 'srv_rerror_rate', 'same_srv_rate', 'diff_srv_rate', 'srv_diff_host_rate', 'dst_host_count', 'dst_host_srv_count', 'dst_host_same_srv_rate', 'dst_host_diff_srv_rate', 'dst_host_same_src_port_rate', 'dst_host_srv_diff_host_rate', 'dst_host_serror_rate', 'dst_host_srv_serror_rate', 'dst_host_rerror_rate', 'dst_host_srv_rerror_rate', 'total_activity', 'protocol_type_tcp', 'protocol_type_udp', 'service_X11', 'service_Z39_50', 'service_auth', 'service_bgp', 'service_courier', 'service_csnet_ns', 'service_ctf', 'service_daytime', 'service_discard', 'service_domain', 'service_domain_u', 'service_echo', 'service_eco_i', 'service_ecr_i', 'service_efs', 'service_exec', 'service_finger', 'service_ftp', 'service_ftp_data', 'service_gopher', 'service_hostnames', 'service_http', 'service_http_443', 'service_http_8001', 'service_imap4', 'service_iso_tsap', 'service_klogin', 'service_kshell', 'service_ldap', 'service_link', 'service_login', 'service_mtp', 'service_name', 'service_netbios_dgm', 'service_netbios_ns', 'service_netbios_ssn', 'service_netstat', 'service_nnsp', 'service_nntp', 'service_ntp_u', 'service_other', 'service_pm_dump', 'service_pop_2', 'service_pop_3', 'service_printer', 'service_private', 'service_red_i', 'service_remote_job', 'service_rje', 'service_shell', 'service_smtp', 'service_sql_net', 'service_ssh', 'service_sunrpc', 'service_supdup', 'service_systat', 'service_telnet', 'service_tim_i', 'service_time', 'service_urh_i', 'service_urp_i', 'service_uucp', 'service_uucp_path', 'service_vmnet', 'service_whois', 'flag_REJ', 'flag_RSTO', 'flag_RSTOS0', 'flag_RSTR', 'flag_S0', 'flag_S1', 'flag_S2', 'flag_S3', 'flag_SF', 'flag_SH', 'class_normal']

---
### Task 5: Format Data

This final preparation task ensures the data is in the correct format for the modelling tools. Activities include:

- **Data Type Conversions:** Ensure all columns have appropriate data types (e.g., numeric, datetime, categorical).
- **Column Reordering:** Arrange columns in a logical order (e.g., features first, target last).
- **Renaming:** Give columns clear, descriptive names.
- **Saving the Prepared Dataset:** Export the final, clean dataset for use in subsequent phases.

**Instructions:** Apply any final formatting changes and save the prepared dataset.

In [80]:
print([col for col in df_integrated.columns if 'class' in col])

['class_normal']

In [81]:
# TODO: Apply final formatting — data types, column order, renaming.

# Example: Convert data types
# df_integrated['some_column'] = df_integrated['some_column'].astype('int')

# Example: Rename columns for clarity
# df_integrated = df_integrated.rename(columns={
#     'old_name': 'new_descriptive_name'
# })

# Example: Reorder columns (target column last)
# target_col = 'target'
# feature_cols = [col for col in df_integrated.columns if col != target_col]
# df_final = df_integrated[feature_cols + [target_col]]
# Set your target column (IMPORTANT — adjust if needed)
target_col = 'class_normal'

feature_cols = [col for col in df_integrated.columns if col != target_col]

df_final = df_integrated[feature_cols + [target_col]]

print("Target column moved to the end")

Target column moved to the end

In [82]:
# TODO: Verify the final prepared dataset.

# print("=" * 60)
# print("FINAL PREPARED DATASET SUMMARY")
# print("=" * 60)
# print(f"Shape: {df_final.shape}")
# print(f"Missing values: {df_final.isnull().sum().sum()}")
# print(f"Duplicates: {df_final.duplicated().sum()}")
# print(f"\nColumn types:")
# print(df_final.dtypes)
# df_final.head()
print("=" * 60)
print("FINAL PREPARED DATASET SUMMARY")
print("=" * 60)

print(f"Shape: {df_final.shape}")
print(f"Missing values: {df_final.isnull().sum().sum()}")
print(f"Duplicates: {df_final.duplicated().sum()}")

print(f"\nColumn types:")
print(df_final.dtypes)

df_final.head()

============================================================
FINAL PREPARED DATASET SUMMARY
============================================================
Shape: (25192, 117)
Missing values: 0
Duplicates: 989

Column types:
duration          float64
src_bytes         float64
dst_bytes         float64
land              float64
wrong_fragment    float64
                   ...
flag_S2              bool
flag_S3              bool
flag_SF              bool
flag_SH              bool
class_normal         bool
Length: 117, dtype: object

,duration,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,num_compromised,root_shell,su_attempted,num_root,num_file_creations,num_shells,num_access_files,num_outbound_cmds,is_host_login,is_guest_login,count,srv_count,serror_rate,srv_serror_rate,rerror_rate,srv_rerror_rate,same_srv_rate,diff_srv_rate,srv_diff_host_rate,dst_host_count,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,total_activity,protocol_type_tcp,protocol_type_udp,service_X11,service_Z39_50,service_auth,service_bgp,service_courier,service_csnet_ns,service_ctf,service_daytime,service_discard,service_domain,service_domain_u,service_echo,service_eco_i,service_ecr_i,service_efs,service_exec,service_finger,service_ftp,service_ftp_data,service_gopher,service_hostnames,service_http,service_http_443,service_http_8001,service_imap4,service_iso_tsap,service_klogin,service_kshell,service_ldap,service_link,service_login,service_mtp,service_name,service_netbios_dgm,service_netbios_ns,service_netbios_ssn,service_netstat,service_nnsp,service_nntp,service_ntp_u,service_other,service_pm_dump,service_pop_2,service_pop_3,service_printer,service_private,service_red_i,service_remote_job,service_rje,service_shell,service_smtp,service_sql_net,service_ssh,service_sunrpc,service_supdup,service_systat,service_telnet,service_tim_i,service_time,service_urh_i,service_urp_i,service_uucp,service_uucp_path,service_vmnet,service_whois,flag_REJ,flag_RSTO,flag_RSTOS0,flag_RSTR,flag_S0,flag_S1,flag_S2,flag_S3,flag_SF,flag_SH,class_normal
0,0.0,1.415223,-0.672625,0.0,0.0,0.0,0.0,0.0,-0.807626,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.758456,-0.801133,-0.640142,-0.633978,0.0,0.0,0.772109,-0.693436,0.0,-0.328634,-0.813985,-0.779157,-0.271725,1.848086,-0.579656,-0.641804,-0.627365,0.0,0.0,-0.376881,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True
1,0.0,-0.113860,-0.672625,0.0,0.0,0.0,0.0,0.0,-0.807626,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.653417,-0.879920,-0.640142,-0.633978,0.0,0.0,-1.320567,2.768934,0.0,0.732059,-1.030895,-1.157831,2.544308,1.848086,-0.579656,-0.641804,-0.627365,0.0,0.0,-0.768314,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True
2,0.0,-0.760950,-0.672625,0.0,0.0,0.0,0.0,0.0,-0.807626,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.396970,-0.485985,1.595477,1.600209,0.0,0.0,-1.388806,0.922337,0.0,0.732059,-0.804947,-0.935081,0.116694,-0.663412,-0.579656,1.603834,1.614454,0.0,0.0,-0.771824,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False
3,0.0,0.267303,1.867994,0.0,0.0,0.0,0.0,0.0,1.238197,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.729809,-0.564772,-0.193018,-0.187141,0.0,0.0,0.772109,-0.693436,0.0,-1.540854,1.264742,1.069663,-0.854352,-0.161113,1.706748,-0.574435,-0.604947,0.0,0.0,1.443263,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True
4,0.0,0.121043,0.132324,0.0,0.0,0.0,0.0,0.0,1.238197,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.491085,1.562475,-0.640142,-0.633978,0.0,0.0,0.772109,-0.693436,0.0,0.732059,1.264742,1.069663,-0.854352,-0.663412,-0.579656,-0.641804,-0.627365,0.0,0.0,0.426048,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True

In [83]:
# TODO: Save the prepared dataset for use in Phase 4 (Modelling).

# OUTPUT_PATH = 'path/to/your/prepared_data.csv'
# df_final.to_csv(OUTPUT_PATH, index=False)
# print(f"Prepared dataset saved to: {OUTPUT_PATH}")
OUTPUT_PATH = "prepared_network_intrusion_data.csv"

df_final.to_csv(OUTPUT_PATH, index=False)

print(f"Prepared dataset saved to: {OUTPUT_PATH}")

Prepared dataset saved to: prepared_network_intrusion_data.csv